{
 "title": "Postgresql CgroupV2 Connection Manager",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cgroup_name",
    "query": {
     "query": "label_values(cgroupv2_metric{job=\"pg_cgroup_manager\"}, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BoundedConnections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cgroupv2_metric{metric=\"pids.current\", path=~\"${cgroup_name}\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "OOM Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cgroupv2_metric{metric=\"oom_events\", path=~\"${cgroup_name}\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cgroupv2_metric{job=\"pg_cgroup_manager\", metric=\"mem_current\", path=~\"${cgroup_name}\"}",
     "legendFormat": "{{metric}}-{{path}}"
    }
   ]
  },
  {
   "title": "Cpu Usage Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "cgroupv2_metric{job=\"pg_cgroup_manager\", metric=\"cpu_usage\", path=~\"${cgroup_name}\"}",
     "legendFormat": "{{metric}}-{{path}}"
    }
   ]
  },
  {
   "title": "Cpu Throttle Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cgroupv2_metric{job=\"pg_cgroup_manager\", metric=\"cpu_throttled\", path=~\"${cgroup_name}\"}",
     "legendFormat": "{{metric}}-{{path}}"
    }
   ]
  }
 ]
}